/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../website/wrangler.redirects.jsonc --include-runtime=false --env-interface=RedirectEnv ../website/workers/redirect-env.d.ts` (hash: 206c56ef22176fe0a5844305b0ae18fa)
interface __BaseEnv_RedirectEnv {
	CANONICAL_ORIGIN: "https://www.fccareer.top";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./redirect");
	}
	interface Env extends __BaseEnv_RedirectEnv {}
}
interface RedirectEnv extends __BaseEnv_RedirectEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CANONICAL_ORIGIN">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}