-- Initial schema for a new FC Career Top MySQL database.
-- Flyway applies this once; put subsequent changes in a new versioned migration.

CREATE TABLE `user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `is_email_verified` tinyint(1) DEFAULT '0',
  `last_send_email_time` datetime DEFAULT NULL,
  `password` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `token` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `is_deleted` tinyint(1) DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `user_secret_key` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `secret_key` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `is_deleted` tinyint(1) DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `user_setting` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `default_game_version` int DEFAULT NULL,
  `enable_notification` tinyint(1) DEFAULT '1',
  `notification_items` text COLLATE utf8mb4_general_ci,
  `is_deleted` tinyint(1) DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `user_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `activity_time` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_activity_time` (`activity_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `player` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `game_version` int DEFAULT NULL,
  `save_id` int DEFAULT NULL,
  `player_id` int DEFAULT NULL,
  `player_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `birthdate` int DEFAULT NULL,
  `age` int DEFAULT NULL,
  `overallrating` int DEFAULT NULL,
  `potential` int DEFAULT NULL,
  `nationality` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `height` int DEFAULT NULL,
  `weight` int DEFAULT NULL,
  `preferredfoot` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `preferredposition1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `preferredposition2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `preferredposition3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `preferredposition4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `skillmoves` int DEFAULT NULL,
  `weakfootabilitytypecode` int DEFAULT NULL,
  `attackingworkrate` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `defensiveworkrate` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `acceleration` int DEFAULT NULL,
  `sprintspeed` int DEFAULT NULL,
  `positioning` int DEFAULT NULL,
  `finishing` int DEFAULT NULL,
  `shotpower` int DEFAULT NULL,
  `longshots` int DEFAULT NULL,
  `volleys` int DEFAULT NULL,
  `penalties` int DEFAULT NULL,
  `vision` int DEFAULT NULL,
  `crossing` int DEFAULT NULL,
  `freekickaccuracy` int DEFAULT NULL,
  `shortpassing` int DEFAULT NULL,
  `longpassing` int DEFAULT NULL,
  `curve` int DEFAULT NULL,
  `agility` int DEFAULT NULL,
  `balance` int DEFAULT NULL,
  `reactions` int DEFAULT NULL,
  `ballcontrol` int DEFAULT NULL,
  `dribbling` int DEFAULT NULL,
  `composure` int DEFAULT NULL,
  `interceptions` int DEFAULT NULL,
  `headingaccuracy` int DEFAULT NULL,
  `defensiveawareness` int DEFAULT NULL,
  `standingtackle` int DEFAULT NULL,
  `slidingtackle` int DEFAULT NULL,
  `jumping` int DEFAULT NULL,
  `stamina` int DEFAULT NULL,
  `strength` int DEFAULT NULL,
  `aggression` int DEFAULT NULL,
  `gkdiving` int DEFAULT NULL,
  `gkhandling` int DEFAULT NULL,
  `gkkicking` int DEFAULT NULL,
  `gkpositioning` int DEFAULT NULL,
  `gkreflexes` int DEFAULT NULL,
  `play_styles` varchar(2000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_archived` int DEFAULT '0',
  `is_deleted` tinyint(1) DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_player_id` (`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `player_status_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `game_version` int DEFAULT NULL,
  `save_id` int DEFAULT NULL,
  `player_id` int DEFAULT NULL,
  `in_game_date` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `overallrating` int DEFAULT NULL,
  `potential` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_player_id` (`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `user_notification` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `game_version` int NOT NULL,
  `in_game_date` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `message_type` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `message_subtype` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `player_id` int NOT NULL,
  `old_overall_rating` int DEFAULT NULL,
  `overall_rating` int DEFAULT NULL,
  `old_potential` int DEFAULT NULL,
  `potential` int DEFAULT NULL,
  `old_skillmoves` int DEFAULT NULL,
  `skillmoves` int DEFAULT NULL,
  `old_weakfoot` int DEFAULT NULL,
  `weakfoot` int DEFAULT NULL,
  `old_play_styles` text COLLATE utf8mb4_general_ci,
  `play_styles` text COLLATE utf8mb4_general_ci,
  `is_read` tinyint(1) DEFAULT '0',
  `is_deleted` tinyint(1) DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_in_game_date` (`in_game_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
